# Created by trellis-cli v1.11.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  alexbracken.test:
    site_hosts:
    - canonical: alexbracken.test
      redirects:
      - www.alexbracken.test
    local_path: ../site
    admin_email: admin@alexbracken.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
